var Global = 
{
	MAX_GROUP_MEMBERS: 5,

	MIN_CLIENT_LEVEL: 1,
	MAX_CLIENT_LEVEL: 100,

	INSTANT_SERVER: false,

	SERVER_RANDOM_LATENCY: true,
	SERVER_RANDOM_LATENCY_MIN: 50,
	SERVER_RANDOM_LATENCY_MAX: 800,

	SERVER_LATENCY_MS: 600
}